[package]
name = "helpers"
version = "0.0.0"
edition = "2021"

[dependencies]
sn_api = { git = "file:///home/z/zone/maidsafe/safe_network", branch = "expose--test_helpers" }

[dev-dependencies]
tokio = "1"
