[package]
name = "helpers"
version = "0.0.0"
edition = "2021"

[dependencies]
sn_client = { git = "https://github.com/DerickEddington/safe_network.git", branch = "kcired/write-only-registers", features = ["test-utils"] }

[dev-dependencies]
tokio = "1"
